# Generated by Django 4.2.2 on 2023-06-13 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="nome",
        ),
    ]
