# Generated by Django 4.2.2 on 2023-06-13 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_remove_user_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watch",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mywatchs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
