# Generated by Django 4.2.2 on 2023-06-15 01:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_remove_watch_user_remove_watch_watchs_watch_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="watch",
            field=models.ManyToManyField(
                related_name="mywatchs", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Watch",
        ),
    ]
