# Generated by Django 4.2.2 on 2023-06-15 01:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_action_watch_delete_watch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="watch",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="mywatchs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
