# Generated by Django 4.2.2 on 2023-06-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_alter_action_watch"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="ended",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
